config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      post 'auth/login'
      post 'auth/refresh'
      post 'auth/valid'
      get 'auth/public_key'
    end
  end

  resources :allowed_apps, only: [:show, :edit, :update, :destroy]

  resources :users do
    get 'allowed_apps', to: 'allowed_apps#index_user'
    resources :allowed_apps, only: [:create]
    member do
      get 'password'
      post 'password', to: 'users#update_password', as: 'update_password'
      get 'reset_user_key'
    end
  end

  resources :apps do
    get 'allowed_apps', to: 'allowed_apps#index_app'
    member do
      get 'reset_app_key'
      get 'reset_rsa_key_pair'
    end
  end

  devise_for :admins, controllers: { registrations: 'registrations', sessions: 'sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'apps#index'
end

app/models/allowed_app.rb
# frozen_string_literal: true

class AllowedApp < ApplicationRecord
  include ::JsonConcern

  JSON_SCHEMA = "#{Rails.root}/app/models/schemas/allowed_app/data.json"

  belongs_to :user
  belongs_to :app
  has_one :refresh_token, dependent: :destroy

  validates :user_id, :app_id, presence: true
  validates :user_id, uniqueness: { scope: :app_id, message: 'only can be associated with an app once.' }
  validates :permissions, json: { schema: :dynamic_app_schema }, on: :update

  serialize :permissions, Hash

  def permissions=(value)
    write_attribute(:permissions, JSON.parse(value))
  rescue StandardError
    write_attribute(:permissions, JSON.parse('{"malformed": ["json"], "value": "' + clean_malformed_json(value) + '"}'))
  end

  def permissions
    read_attribute(:permissions).to_json
  end

  def permissions_valid?
    not ((not valid?) and errors.messages[:permissions] and errors.messages[:permissions].include? 'JSON Schema Invalid')
  end

  def need_suggestion?
    permissions == '{}' and not(permissions_valid?)
  end

  def permissions_or_suggestion
    if need_suggestion?
      PermissionsSuggestion.new(app.permissions).call.to_json
    else
      permissions
    end
  end

  private

  def dynamic_app_schema
    DynamicSchema.new(app.permissions).call
  end
end

app/controllers/allowed_apps_controller.rb
class AllowedAppsController < ApplicationController

  before_action :set_allowed_app, only: [:destroy, :show, :edit, :update]
  before_action :set_app, only: [:index_app]
  before_action :set_user, only: [:index_user, :create]
  before_action :set_available_apps, only: [:index_user]

  before_action :set_fullpage, only: [:index_user, :index_app]

  def index_app
    @allowed_apps = @app.allowed_apps
  end

  def index_user
    @allowed_app = AllowedApp.new
  end

  def create
    @allowed_app = @user.allowed_apps.create(allowed_app_params)
    redirect_to user_allowed_apps_path(@user), notice: 'App was successfully added.'
  rescue ActionController::ParameterMissing => e
    redirect_to user_allowed_apps_path(@user), alert: 'Something went wrong, no App added.'
  end

  def update
    if @allowed_app.update(allowed_app_params)
      redirect_to allowed_app_path(@allowed_app), notice: 'Allowed app was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /allowed_apps/1
  # DELETE /allowed_apps/1.json
  def destroy

    @allowed_app.destroy
    redirect_back fallback_location: root_path
  end

  private

  def set_allowed_app
    @allowed_app = AllowedApp.find(params[:id])
    @user        = @allowed_app.user
    @app         = @allowed_app.app
  end

  def set_app
    @app = App.find(params[:app_id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_available_apps
    @available_apps = App.where.not(id: @user.apps)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def allowed_app_params
    params.require(:allowed_app).permit(:app_id, :permissions)
  end
end

app/helpers/allowed_apps_helper.rb
module AllowedAppsHelper
end

app/views/allowed_apps/_app_link.html.erb
<% if @app %>
  <h4>App: <%= link_to @app.name, app_path(@app) %></h4>
<% end %>

app/views/allowed_apps/_form.html.erb
<%= form_with(model: allowed_app, local: true) do |form| %>
  <% if allowed_app.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(allowed_app.errors.count, "error") %> prohibited this allowed_app from being saved:</h4>

      <ul>
      <% allowed_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="col-sm-6">
      <div class="field">
        <%= form.label :permissions %>
        <%= form.text_area(:permissions, size: '50x10', value: json_pretty_generate(allowed_app.permissions_or_suggestion)) %>
        <%= content_tag :strong, '(Automatic Suggestion)' if allowed_app.need_suggestion? %>
      </div>
    </div>
    <div class="col-sm-6">
      <%= render 'apps/show_schema', app: @allowed_app.app %>
    </div>
  </div>


  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/allowed_apps/_new_form.html.erb
<%= form_with(model: allowed_app, url: [@user, allowed_app], local: true) do |form| %>
  <% if allowed_app.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(allowed_app.errors.count, "error") %> prohibited this allowed_app from being saved:</h4>

      <ul>
      <% allowed_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
   <div class="col-sm-2">
      <%= form.label :app_id %>
   </div>
   <div class="col-sm-2">
      <%= form.select(:app_id, options_from_collection_for_select(@available_apps, :id, :name), {},{class: "form-control"}) %>
   </div>
</div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary', disabled: @available_apps.empty? %>
  </div>
<% end %>

app/views/allowed_apps/_user_app_status.html.erb
<%= render 'user_link'%>
<%= render 'app_link'%>

<% if @allowed_app %>
  <h4>Status: <%= permission_state(@allowed_app) %></h4>
<% end %>

app/views/allowed_apps/_user_link.html.erb
<% if @user %>
  <h4>User: <%= link_to "#{@user.name} - #{@user.email}", user_path(@user) %></h4>
<% end %>

app/views/allowed_apps/edit.html.erb
<%= render 'user_app_status' %>

<h1>Editing Allowed App</h1>

<%= render 'form', allowed_app: @allowed_app %>

<% content_for :operations do %>
<%= link_to 'Show', allowed_app_path(@allowed_app), class: 'btn btn-primary' %>
<% end %>

app/views/allowed_apps/index_app.html.erb
<%= render 'app_link' %>

<h1>Users</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Permissions</th>
      <th>Valid Permissions</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @app.allowed_apps.each do |allowed_app| %>
      <tr>
        <td class="table-cell" data-href="<%= allowed_app_path(allowed_app) %>">
          <%= allowed_app.user.name %>
        </td>
        <td class="table-cell" data-href="<%= allowed_app_path(allowed_app) %>">
<pre>
<small><%= json_pretty_generate(allowed_app.permissions) %></small>
</pre>        </td>
        <td class="table-cell" data-href="<%= allowed_app_path(allowed_app) %>">
          <%= permission_state(allowed_app) %><%=  %>
        </td>
        <td><%= link_to 'Edit', edit_allowed_app_path(allowed_app), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', allowed_app_path(allowed_app), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/allowed_apps/index_user.html.erb
<%= render 'user_link' %>

<h1>Allowed Apps</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>App</th>
      <th>Permissions</th>
      <th>Valid Permissions</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.allowed_apps.select(&:persisted?).each do |allowed_app| %>
      <tr>
        <td class="table-cell" data-href="<%= allowed_app_path(allowed_app) %>">
          <%= allowed_app.app.name %>
        </td>
        <td class="table-cell" data-href="<%= allowed_app_path(allowed_app) %>">
<pre>
<small><%= json_pretty_generate(allowed_app.permissions) %></small>
</pre>        </td>
        <td class="table-cell" data-href="<%= allowed_app_path(allowed_app) %>">
          <%= permission_state(allowed_app) %><%=  %>
        </td>
        <td><%= link_to 'Edit', edit_allowed_app_path(allowed_app), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', allowed_app_path(allowed_app), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h2>Add App</h2>
<div class="card card-body bg-light">
<%= render 'new_form', allowed_app: @allowed_app %>
</div>

app/views/allowed_apps/show.html.erb
<%= render 'user_app_status' %>

<table class="table">
<tr>
  <td>
  <strong>Permissions:</strong>
<pre style="margin-top: 8px;">
<%= json_pretty_generate(@allowed_app.permissions) %>
</pre>
  </td>
  <td>
<%= render 'apps/show_schema', app: @allowed_app.app %>
  </td>
</tr>
</table>

<% content_for :operations do %>
<%= link_to "Apps for <strong>#{@allowed_app.user.name}</strong>".html_safe, user_allowed_apps_path(@allowed_app.user), class: 'btn btn-info' %>
<%= link_to "Users for <strong>#{@allowed_app.app.name}</strong>".html_safe, app_allowed_apps_path(@allowed_app.app), class: 'btn btn-info' %>
<% end %>


<% content_for :footer do %>
<%= link_to 'Edit', edit_allowed_app_path(@allowed_app), class: 'btn btn-primary' %>
<% end %>