config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      post 'auth/login'
      post 'auth/refresh'
      post 'auth/valid'
      get 'auth/public_key'
    end
  end

  resources :allowed_apps, only: [:show, :edit, :update, :destroy]

  resources :users do
    get 'allowed_apps', to: 'allowed_apps#index_user'
    resources :allowed_apps, only: [:create]
    member do
      get 'password'
      post 'password', to: 'users#update_password', as: 'update_password'
      get 'reset_user_key'
    end
  end

  resources :apps do
    get 'allowed_apps', to: 'allowed_apps#index_app'
    member do
      get 'reset_app_key'
      get 'reset_rsa_key_pair'
    end
  end

  devise_for :admins, controllers: { registrations: 'registrations', sessions: 'sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'apps#index'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include ::PermissionsConcern

  attr_reader :password
  has_many :allowed_apps, dependent: :destroy
  has_many :apps, through: :allowed_apps

  before_validation :set_secrets, on: :create

  validates :name, :user_key, uniqueness: true, presence: true
  validates :email, email: true, uniqueness: true, presence: true

  validates :password, length: { minimum: 6 }, allow_nil: true

  scope :enabled, -> { where(enabled: true) }
  scope :password_setted, -> { where.not(encrypted_password: nil) }

  def self.email_with_password(email, password)
    user = enabled.password_setted.where(email: email).take
    return nil if user.nil?

    user if user.encrypted_password == BCrypt::Engine.hash_secret(password, user.salt)
  end

  def password=(password)
    @password = password
    self.encrypted_password = BCrypt::Engine.hash_secret(password, salt) if password && valid?
  end

  def password_setted?
    !encrypted_password.nil?
  end

  def reset_user_key
    update_attribute(:user_key, SecretGenerator.generate(64))
  end

  def jwt_attributes
    {
      name: name,
      email: email
    }
  end

  private

  def set_secrets
    self.user_key = SecretGenerator.generate(64)
    self.salt = BCrypt::Engine.generate_salt
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :password, :update_password, :reset_user_key]
  before_action :set_fullpage, only: [:index]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params_update)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def password
  end

  def update_password
    respond_to do |format|
      if @user.update(user_params_password)
        format.html { redirect_to @user, notice: 'User password was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :password }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def reset_user_key
    @user.reset_user_key
    redirect_to @user, notice: 'User Key was successfully updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :enabled, :email)
    end

    def user_params_update
      params.require(:user).permit(:name, :enabled)
    end
    
    def user_params_password
      params.permit(:password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
      <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control', disabled: user.persisted? %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :enabled %>
    <%= form.check_box :enabled, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<% content_for :operations do %>
<%= link_to 'Show', @user, class: 'btn btn-primary' %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Enabled</th>
      <th>Password Setted</th>
      <th>Apps</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="table-cell" data-href="<%= user_path(user) %>">
          <%= user.name %>
        </td>
        <td class="table-cell" data-href="<%= user_path(user) %>">
          <%= user.email %>
        </td>
        <td class="table-cell" data-href="<%= user_path(user) %>">
          <%= enabled_icon(user.enabled) %>
        </td>
        <td class="table-cell" data-href="<%= user_path(user) %>">
          <%= user.password_setted? %>
        </td>
        <td class="table-cell" data-href="<%= user_path(user) %>">
          <%= show_permissions_state(user.permissions_state) %>
        </td>
        <td><%= link_to 'Configure Apps', user_allowed_apps_path(user), class: 'btn btn-info' %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% content_for :footer do %>
<%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/password.html.erb
<h1>Editing User Password</h1>

<%= form_with(url: update_password_user_path(@user), local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<dl class="row">
  <dt class="col-sm-3">
    Name:
  </dt>
  <dd class="col-sm-9">
      <%= @user.name %>
  </dd>
  <dt class="col-sm-3">
    Email:
  </dt>
  <dd class="col-sm-9">
      <%= @user.email %>
  </dd>
</dl>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.text_field :password, class: 'form-control' %>
  </div>


  <div class="actions">
    <%= form.submit class: 'btn btn-primary'%>
  </div>
<% end %>

<% content_for :operations do %>
<%= link_to 'Show', @user, class: 'btn btn-primary' %>
<% end %>

app/views/users/show.html.erb
<dl class="row">
  <dt class="col-sm-3">
    Email:
  </dt>
  <dd class="col-sm-9">
    <h4>
      <%= @user.email %>
    </h4>
  </dd>
  <dt class="col-sm-3">
    Name:
  </dt>
  <dd class="col-sm-9">
      <%= @user.name %>
  </dd>
  <dt class="col-sm-3">
    Enabled:
  </dt>
  <dd class="col-sm-9">
     <%= enabled_icon(@user.enabled) %>
  </dd>
  <dt class="col-sm-3">
    User key:
  </dt>
  <dd class="col-sm-9">
      <%= @user.user_key %>
  </dd>
  <dt class="col-sm-3">
    Password Setted:
  </dt>
  <dd class="col-sm-9">
      <%= @user.password_setted? %>
  </dd>
  <dt class="col-sm-3">
    Apps:
  </dt>
  <dd class="col-sm-9">
      <%= @user.allowed_apps.map { |allowed_app| link_to "#{allowed_app.app.name} #{permission_state(allowed_app)}".html_safe, allowed_app_path(allowed_app) }.join(' ').html_safe %>
  </dd>
</dl>

<% content_for :footer do %>
<%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary' %>
<% end %>

<% content_for :operations do %>
<%= link_to 'Set Password', password_user_path(@user), class: 'btn btn-primary' %>
<%= link_to 'Reset User Key', reset_user_key_user_path(@user), data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<%= link_to 'Configure Apps', user_allowed_apps_path(@user), class: 'btn btn-info' %>
<% end %>