config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      post 'auth/login'
      post 'auth/refresh'
      post 'auth/valid'
      get 'auth/public_key'
    end
  end

  resources :allowed_apps, only: [:show, :edit, :update, :destroy]

  resources :users do
    get 'allowed_apps', to: 'allowed_apps#index_user'
    resources :allowed_apps, only: [:create]
    member do
      get 'password'
      post 'password', to: 'users#update_password', as: 'update_password'
      get 'reset_user_key'
    end
  end

  resources :apps do
    get 'allowed_apps', to: 'allowed_apps#index_app'
    member do
      get 'reset_app_key'
      get 'reset_rsa_key_pair'
    end
  end

  devise_for :admins, controllers: { registrations: 'registrations', sessions: 'sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'apps#index'
end

app/views/apps/_form.html.erb
<%= form_with(model: app, local: true) do |form| %>
  <% if app.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(app.errors.count, "error") %> prohibited this app from being saved:</h4>

      <ul>
      <% app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :permissions %>
    <%= form.text_area(:permissions, size: '50x8', value: json_pretty_generate(app.permissions), class: 'form-control') %>
  </div>
  <div class="form-group">
    <%= form.label :timeout %>
    <%= form.number_field :timeout, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/apps/_json_permission_reference.html.erb
<pre>
For Permissions uou can use:

- Array
"role": ["admin", "user"]

- String
"internal_code": "string"

- Integer
"quantity": "integer"

- Boolean
"enabled": "boolean"
</pre>

app/views/apps/_show_schema.erb
<strong><%= app.name %></strong> Schema:
<pre style="margin-top: 8px;">
<%= json_pretty_generate(app.permissions) %>
</pre>

app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form', app: @app %>

<% content_for :operations do %>
  <%= link_to 'Show', @app, class: 'btn btn-primary' %>
  <p>
  <%= render partial: 'json_permission_reference'%>
  </p>
<% end %>

app/views/apps/index.html.erb
<h1>Apps</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Permissions</th>
      <th>Timeout</th>
      <th>Users</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td class="table-cell" data-href="<%= app_path(app) %>">
          <%= app.name %>
        </td>
        <td class="table-cell" data-href="<%= app_path(app) %>">
<pre>
<small><%= json_pretty_generate(app.permissions) %></small>
</pre>
        </td>
        <td class="table-cell" data-href="<%= app_path(app) %>">
          <%= app.timeout %>
        </td>
        <td class="table-cell" data-href="<%= app_path(app) %>">
          <%= show_permissions_state(app.permissions_state) %>
        </td>
        <td><%= link_to 'Users', app_allowed_apps_path(app), class: 'btn btn-info' %></td>
        <td><%= link_to 'Edit', edit_app_path(app), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% content_for :footer do %>
<%= link_to 'New App', new_app_path, class: 'btn btn-primary' %>
<% end %>

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form', app: @app %>

<% content_for :operations do %>
<%= render partial: 'json_permission_reference'%>
<% end %>

app/views/apps/show.html.erb
<dl class="row">
  <dt class="col-sm-3">
    Name:
  </dt>
  <dd class="col-sm-9">
    <h4>
      <%= @app.name %>
    </h4>
  </dd>
  <dt class="col-sm-3">
    Permissions:
  </dt>
  <dd class="col-sm-9">
<pre>
<%= json_pretty_generate(@app.permissions) %>
</pre>
  </dd>
  <dt class="col-sm-3">
    RSA Public Key:
  </dt>
  <dd class="col-sm-9" style="word-wrap: break-word;">
<pre>
<%= @app.rsa_public_key %>
</pre>
  </dd>
  <dt class="col-sm-3">
    API Access JWT:
  </dt>
  <dd class="col-sm-9" style="word-wrap: break-word;">
<pre>
<%= @app.api_jwt %>
</pre>
  </dd>
  <dt class="col-sm-3">
    Timeout:
  </dt>
  <dd class="col-sm-9" style="word-wrap: break-word;">
      <%= @app.timeout %>
  </dd>
  <dt class="col-sm-3">
    Users:
  </dt>
  <dd class="col-sm-9" style="word-wrap: break-word;">
     <%= @app.allowed_apps.map { |allowed_app| link_to "#{allowed_app.user.name} #{permission_state(allowed_app)}".html_safe, allowed_app_path(allowed_app) }.join(' ').html_safe %>
  </dd>
</dl>

<% content_for :footer do %>
<%= link_to 'Edit', edit_app_path(@app), class: 'btn btn-primary' %>
<% end %>

<% content_for :operations do %>
    <%= link_to 'Reset API Access JWT', reset_app_key_app_path(@app), data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
    <%= link_to 'Reset RSA Key pair', reset_rsa_key_pair_app_path(@app), data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
    <%= link_to 'Destroy', @app, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    <%= link_to 'Users', app_allowed_apps_path(@app), class: 'btn btn-info' %>
<% end %>