config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      post 'auth/login'
      post 'auth/refresh'
      post 'auth/valid'
      get 'auth/public_key'
    end
  end

  resources :allowed_apps, only: [:show, :edit, :update, :destroy]

  resources :users do
    get 'allowed_apps', to: 'allowed_apps#index_user'
    resources :allowed_apps, only: [:create]
    member do
      get 'password'
      post 'password', to: 'users#update_password', as: 'update_password'
      get 'reset_user_key'
    end
  end

  resources :apps do
    get 'allowed_apps', to: 'allowed_apps#index_app'
    member do
      get 'reset_app_key'
      get 'reset_rsa_key_pair'
    end
  end

  devise_for :admins, controllers: { registrations: 'registrations', sessions: 'sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'apps#index'
end

app/views/layouts/_head_section.html.erb
    <title>JWT Auth</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="JLB">
    <meta name="generator" content="Jekyll v3.8.5">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <%= link_to "JWT Auth", root_path, class: "navbar-brand col-sm-3 col-md-2 mr-0" %>
  <ul class="navbar-nav px-3">
        <% if current_admin %>
          <li class="nav-item text-nowrap"><%= link_to "Sign Out", destroy_admin_session_path, method: :delete, class: 'nav-link' %></li>
        <% else %>
          <li class="nav-item text-nowrap"><%= link_to "Sign In", new_admin_session_path, class: 'nav-link' %></li>
        <% end %>
  </ul>
</nav>

app/views/layouts/_post_yield.html.erb
        </main>
        </div><!-- row -->
          <div class="row">
            <div class="col-md-9 ml-sm-auto col-lg-10 px-4" id="div-footer">
              <%= yield :footer %>
            </div>
          </div>
          
    </div><!-- container-fluid -->
  </body>
</html>

app/views/layouts/_pre_yield.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/head_section" %>
  </head>
  <body>
    <%= render "layouts/nav" %>
    <div class="container-fluid">
        <div class="row">
          <%= render "layouts/sidebar" %>
            <main role="main" class="col-md-10 ml-sm-auto col-lg-10 px-4">
               <%= render "shared/flash_messages" %>

app/views/layouts/_sidebar.html.erb
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item" >
            <%= link_to apps_path, class: [:'nav-link', class_active('apps')] do %>
            <%= icon('fas', 'box') %> 
            Apps
            <% end %>
          </li>
          <li class="nav-item" >
            <%= link_to users_path, class: [:'nav-link', class_active('users')] do %>
            <%= icon('fas', 'users') %> 
            Users
            <% end %>
          </li>
        </ul>
      </div>
    </nav>

app/views/layouts/application.html.erb
  <%= render "layouts/pre_yield" %>
      <% if @fullpage %>
            <%= yield %>
      <% else %>
          <div class="row">
            <div class="col-sm-9">
              <%= yield %>
            </div>
            <div class="col-sm-3" id="div-operations">
              <%= yield :operations %>
            </div>
          </div>
      <% end%>
  <%= render "layouts/post_yield" %>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/head_section" %>
    <%= stylesheet_link_tag 'signin', media: 'all', 'data-turbolinks-track' => true %>

  </head>  <body class="text-center">
    <div class="container-fluid">
      <%= render "shared/flash_messages" %>
        <div class="row">
            <%= yield %>
        </div><!-- row -->
    </div><!-- container-fluid -->
  </body>
</html>